---
anchors:
  busybox_image_resource: &busybox_image_resource
    type: docker-image
    source:
      repository: busybox
      tag: 1.31.0


resource_types:
- name: hashicorp-release
  type: docker-image
  source:
    repository: starkandwayne/hashicorp-release-resource

resources:
- name: repository
  type: git
  source:
    uri: git@github.com:saedalavinia/kf-docker.git
    branch: master
    private_key: |
     ((git_private_key))


- name: tag
  type: semver
  source:
    driver: git
    uri: git@github.com:saedalavinia/kf-docker.git
    branch: version
    file: tag
    initial_version: 0.0.0
    private_key: |
     ((git_private_key))

- name: kf-docker
  type: docker-image
  source:
    username:   saedalav
    password:   ((image_repo_secret))
    repository: saedalav/kf


jobs:
- name: docker-build
  serial: true
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: tag
      params:
        bump: patch
    - get: repository
      trigger: true
  - put: kf-docker
    params:
      build: builddir
      tag_file: tag/version
  - put: tag
    inputs: [tag]
    params:
      file: tag/version
      bump: patch



  ## Manually bump a minor version 
- name: bump-minor
  serial: true
  serial_groups: [version]
  plan:
  - put: tag
    params: {bump: minor}


  ## Manually bump a major version 
- name: bump-major
  serial: true
  serial_groups: [version]
  plan:
  - put: tag
    params: {bump: major}
