---


resource_types:
- name: hashicorp-release
  type: docker-image
  source:
    repository: starkandwayne/hashicorp-release-resource

resources:
- name: repository
  type: git
  source:
    uri: git@github.com:saedalavinia/kf-docker.git
    branch: master
    depth: 1
    private_key: |
     ((git_private_key))


- name: alpine
  type: docker-image
  source:
    repository: alpine
    tag: latest

- name: tag
  type: semver
  source:
    driver: git
    uri: git@github.com:saedalavinia/kf-docker.git
    branch: version
    file: tag
    initial_version: 0.0.0
    private_key: |
     ((git_private_key))

- name: kf-docker
  type: docker-image
  source:
    username:   saedalav
    password:   ((image_repo_secret))
    repository: saedalav/kf


jobs:
- name: docker-build
  serial: true
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: repository
      trigger: true
    - get: tag
      params:
        bump: patch
    - get: alpine
      trigger: true
  - task: copy-artifacts
    file: repository/tasks/copy.yml
    image: alpine
  - put: kf-docker
    params:
      build: builddir
      tag_file: tag/version
      tag_as_latest: true
  - put: tag
    inputs: [tag]
    params:
      file: tag/version
      bump: patch



  ## Manually bump a minor version 
- name: bump-minor
  serial: true
  serial_groups: [version]
  plan:
  - put: tag
    params: {bump: minor}


  ## Manually bump a major version 
- name: bump-major
  serial: true
  serial_groups: [version]
  plan:
  - put: tag
    params: {bump: major}
