---

resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: repository
  type: git
  source:
    uri: git@github.com:saedalavinia/kf-docker.git
    branch: master
    depth: 1
    private_key: |
     ((git_private_key))

- name: tag
  type: semver
  source:
    driver: git
    uri: git@github.com:saedalavinia/kf-docker.git
    branch: version
    file: tag
    initial_version: 0.0.0
    private_key: |
     ((git_private_key))

- name: alpine
  type: docker-image
  source:
    repository: alpine
    tag: latest

- name: kf
  type: docker-image
  source:
    username:   saedalav
    password:   ((image_repo_secret))
    repository: saedalav/kf

- name: gcloud-release
  type: file-url
  source:
    url: https://cloud.google.com/sdk/docs/#linux.htlm
    filename: release-version

- name: jq-github-release
  type: github-release
  source:
    owner: stedolan
    repository: jq

- name: kubectl-release
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt 
    filename: kubectl-version

- name: kf-cli-release
  type: file-url
  source:
    url: https://storage.googleapis.com/artifacts.kf-releases.appspot.com/nightly-builds/cli/kf-linux-latest
    filename: kf

jobs:
- name: docker-build
  serial: true
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: repository
      trigger: true
    - get: tag-rc
      resource: tag
      params:
        bump: patch
        pre: rc
        pre_without_version: true
    - get: tag
      resource: tag
      params:
        bump: patch        
    - get: alpine
      trigger: true
      params: {save: true}
    - get: jq-github-release
      trigger: true
    - get: kubectl-release
      trigger: true
    - get: kf-cli-release
      trigger: true
    - get: gcloud-release
      trigger: true
  - task: copy-artifacts
    file: repository/tasks/copy.yml
    image: alpine
  - put: kf
    params:
      load_base: alpine
      build: builddir
      tag_file: tag-rc/version
    get_params: {save: true}
  - task: sanity-test
    file: repository/tasks/test.yml
    image: kf
  - put: kf
    params:
      load: kf
      build: builddir
      tag_file: tag/version
      tag_as_latest: true
    get_params: {skip_download: true}
  - put: tag
    inputs: [tag]
    params:
      file: tag/version
      bump: patch



  ## Manually bump a minor version 
- name: bump-minor
  serial: true
  serial_groups: [version]
  plan:
  - put: tag
    params: {bump: minor}


  ## Manually bump a major version 
- name: bump-major
  serial: true
  serial_groups: [version]
  plan:
  - put: tag
    params: {bump: major}
