---
platform: linux

image_resource:
  type: docker-image
  source:
      repository: alpine
      tag: latest

inputs:
- name: repository

outputs:
- name: builddir

run:
  path:  repository/scripts/copy.sh